### ISSUE TITLE
MVP jQuery: Submit your concern and Close the gap

### ISSUE THREAD

**Issue by MisaZander** [MisaZander/giterdone#8]
Time to wire up some event listeners to the modal submit buttons. There are three separate submit buttons that make three separate POSTS requests. 
- Add Category Item: The event listeners wired to button ids inputTodoSubmit, inputErrandSubmit, and inputCorrSubmit should extract all the juicy data and send a POST request to the relevant api with that data. Do NOT reload the page on this button request.

- Close modal button: Each close button in the modals should force the page to reload when invoked so the categories are repopulated

**Comment by MisaZander** [comment]
The submit functionality seems to be good, the close functionality should work when #6 is merged

**Comment by Crhodes92** [comment]
Complete on issue #8
